version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./"
    target-branch: sveltekit
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    target-branch: sveltekit
    schedule:
      interval: "weekly"
